'use strict';

/**
 * The events a template can name, with the targets each belongs to, and the
 * placeholders a body can use. The names are the reference platform's.
 *
 * Events the platform has no source for (cards, payment and collection
 * orders, data access requests) are left out: a template for them would
 * never send (docs/audits/audit-webhooks.md, finding 2).
 */

const T = (targets, ...events) => events.map((e) => [e, targets]);

const EVENTS = Object.fromEntries([
  ...T(['CLIENT'], 'CLIENT_CREATED', 'CLIENT_APPROVED', 'CLIENT_REJECTED', 'CLIENT_ACTIVITY', 'PORTAL_ACTIVATED'),
  ...T(['GROUP'], 'GROUP_CREATED', 'GROUP_ACTIVITY'),
  ...T(['CLIENT', 'GROUP'], 'CREDIT_ARRANGEMENT_CREATED', 'CREDIT_ARRANGEMENT_EDITED', 'CREDIT_ARRANGEMENT_APPROVED',
    'CREDIT_ARRANGEMENT_REJECTED', 'CREDIT_ARRANGEMENT_WITHDRAWN', 'CREDIT_ARRANGEMENT_CLOSED', 'CREDIT_ARRANGEMENT_DELETED',
    'CREDIT_ARRANGEMENT_ACCOUNT_ADDED', 'CREDIT_ARRANGEMENT_ACCOUNT_REMOVED'),
  ...T(['LOANS'], 'LOAN_CREATED', 'LOAN_APPROVAL', 'LOAN_ACCOUNT_REJECTION', 'LOAN_ACCOUNT_CLOSURE', 'LOAN_ACCOUNT_WRITE_OFF',
    'LOAN_ACCOUNT_RESCHEDULED', 'LOAN_ACCOUNT_REFINANCED', 'LOAN_ACCOUNT_ACTIVITY', 'INTEREST_RATE_CHANGED',
    'LOAN_DISBURSEMENT', 'LOAN_DISBURSEMENT_REVERSAL', 'LOAN_REPAYMENT', 'LOAN_REPAYMENT_REVERSAL', 'FEE_APPLIED', 'FEE_ADJUSTED',
    'PENALTY_ADJUSTMENT', 'CREDIT_BALANCE_DEPOSIT', 'REPAYMENT_REMINDER'),
  ...T(['SAVINGS'], 'SAVINGS_CREATED', 'SAVINGS_APPROVAL', 'SAVINGS_ACCOUNT_ACTIVATED', 'SAVINGS_ACCOUNT_REJECTION',
    'SAVINGS_ACCOUNT_CLOSURE', 'SAVINGS_ACCOUNT_ACTIVITY', 'SAVINGS_DEPOSIT', 'SAVINGS_DEPOSIT_REVERSAL', 'SAVINGS_WITHDRAWAL',
    'SAVINGS_WITHDRAWAL_REVERSAL', 'DEPOSIT_INTEREST_APPLIED'),
  ...T(['LOANS', 'SAVINGS'], 'ACCOUNT_IN_ARREARS'),
  ...T(['ACCOUNTING'], 'JOURNAL_ENTRY_ADDED', 'JOURNAL_ENTRY_ADJUSTED'),
  ...T(['BACKGROUND_PROCESS'], 'END_OF_DAY_PROCESSING_COMPLETED'),
  ...T(['ADMINISTRATIVE'], 'HOLIDAY_SYNC_COMPLETED'),
]);

// The reference platform's other events: named so a template for one is
// refused with a reason, not as unknown.
const NOT_SUPPORTED = ['CARDS_AUTHORISATION_HOLD_CREATED', 'CARDS_AUTHORISATION_HOLD_IN_BULK_CREATED', 'CARDS_AUTHORISATION_HOLD_AMOUNT_INCREASED',
  'CARDS_AUTHORISATION_HOLD_AMOUNT_DECREASED', 'CARDS_AUTHORISATION_HOLD_EXPIRED', 'CARDS_AUTHORISATION_HOLD_REVERSED',
  'CARDS_AUTHORISATION_HOLD_SETTLED', 'CARD_DEPOSIT_REVERSAL', 'CARD_WITHDRAWAL_REVERSAL', 'PAYMENT_ORDER_ACTIVITY',
  'COLLECTION_ORDER_ACTIVITY', 'DATA_ACCESS_STATE_CHANGED', 'PORTAL_PASSWORD_RESET', 'PENALTY_APPLIED', 'FEE_CHARGED',
  'FEES_DUE_REDUCED', 'FEE_REDUCTION_ADJUSTMENT', 'LOAN_ANTICIPATED_DISBURSEMENT', 'REAPPLIED_SAVINGS_DEPOSIT',
  'REAPPLIED_SAVINGS_WITHDRAWAL', 'DEPOSIT_INTEREST_APPLIED_ADJUSTMENT', 'SAVINGS_TRANSACTION_EDITED',
  'ACCOUNT_AUTHORISATION_HOLD_CREATED', 'ACCOUNT_AUTHORISATION_HOLD_REVERSED', 'ACCOUNT_AUTHORISATION_HOLD_SETTLED'];

const TARGETS = ['CLIENT', 'GROUP', 'LOANS', 'SAVINGS', 'BACKGROUND_PROCESS', 'DATA_ACCESS', 'PAYMENT_ORDER', 'ACCOUNTING', 'ADMINISTRATIVE'];

// Placeholders, with a sample value for checking a body when it is saved.
const PLACEHOLDERS = {
  EVENT: 'SAVINGS_DEPOSIT', ACTIVITY_TYPE: 'SAVINGS_ACCOUNT_EDITED', ORGANIZATION_NAME: 'Sample SACCO', CURRENCY_CODE: 'KES',
  CURRENT_DATE: '2026-01-31', SYSTEM_DATE: '2026-01-31T09:30:00Z',
  CLIENT_KEY: '00000000-0000-0000-0000-000000000000', CLIENT_ID: 'M000001', CLIENT_NAME: 'Jane Sample', FIRST_NAME: 'Jane',
  MIDDLE_NAME: '', LAST_NAME: 'Sample', GROUP_NAME: 'Sample Group', MOBILE_PHONE: '0700000000', EMAIL_ADDRESS: 'jane@example.org',
  BRANCH_ID: 'HQ', BRANCH_NAME: 'Head office', RECIPIENT_NAME: 'Jane Sample',
  ACCOUNT_KEY: '00000000-0000-0000-0000-000000000000', ACCOUNT_ID: 'SV000001', ACCOUNT_NAME: 'Savings', ACCOUNT_STATE: 'ACTIVE',
  PRODUCT_ID: 'SAV01', PRODUCT_NAME: 'Savings', TOTAL_BALANCE: '1000.00', AVAILABLE_BALANCE: '1000.00',
  TRANSACTION_KEY: '00000000-0000-0000-0000-000000000000', TRANSACTION_ID: 'SD-SAMPLE', TRANSACTION_TYPE: 'SAVINGS_DEPOSIT',
  TRANSACTION_AMOUNT: '1000.00', TRANSACTION_VALUE_DATE: '2026-01-31', TRANSACTION_CHANNEL: 'cash', REVERSAL_OF: '',
  LOAN_AMOUNT: '12000.00', PRINCIPAL_BALANCE: '12000.00', INTEREST_RATE: '1.5', DISBURSEMENT_DATE: '2026-01-31',
  INSTALLMENT_NUMBER: '1', INSTALLMENT_DUE_DATE: '2026-02-28', INSTALLMENT_DUE_AMOUNT: '2180.00', PRINCIPAL_DUE: '2000.00',
  INTEREST_DUE: '180.00', DAYS_IN_ARREARS: '0',
  CREDIT_ARRANGEMENT_ID: 'CA000001', JOURNAL_ENTRY_ID: '00000000-0000-0000-0000-000000000000', BUSINESS_DATE: '2026-01-31',
};

const targetsOf = (event) => EVENTS[event] || null;

module.exports = { EVENTS, NOT_SUPPORTED, TARGETS, PLACEHOLDERS, targetsOf };
